apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b64yi7q3r-dotnet-basic
  janus-idp.io/tekton: b64yi7q3r-dotnet-basic
  backstage.io/kubernetes-id: b64yi7q3r-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b64yi7q3r-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
